toolbar:
  - undo redo | insert | styleselect | bold italic forecolor backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image
plugins:
  - advlist
  - autolink
  - lists
  - link
  - image
  - charmap
  - print
  - preview
  - hr
  - anchor
  - pagebreak
  - searchreplace
  - wordcount
  - visualblocks
  - visualchars
  - code
  - fullscreen
  - insertdatetime
  - media
  - nonbreaking
  - save
  - table
  - contextmenu
  - directionality
  - paste
  - textcolor
  - colorpicker
  - textpattern
  - imagetools
